# Generated by Django 5.2.1 on 2025-05-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoList", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="srNo",
            new_name="srno",
        ),
    ]
